version: '2'
services:
    mongodb:
        image: 'mongo'
    web:
        image: 'lissonpsantos2/ubuntu-phps'
        ports:
            - '8080:80'
            - '8082:3001'
        volumes:
            - './:/home/project-folder/'
        depends_on:
            - mongodb
        stdin_open: true
        tty: true

